### ISSUE TITLE
nei update 能不能添加参数不脚手架模板或者增加脚手架（对应js 、common/*.ftl等）路径的配置

### ISSUE THREAD

**Issue by triboby** [genify/nei#4]
一、我们实际的模板路径跟nei生成的不一样   

二、多人合作的时候一个人nei录了一个新的页面，然后他本地在开发没提交代码，另一个人本地nei update生成了这个模板 但他不知道这个是不是他需要的 然后就产生了问题

**Comment by huntbao** [comment]
This issue was moved to NEYouFan/nei-toolkit#3
